[package]
name = "tuify"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
color-eyre = "0.6.5"
crossterm = "0.29.0"
open = "5.3.3"
rand = "0.10.0"
ratatui = "0.30.0"
sha2 = "0.10.9"
tiny_http = "0.12.0"
